"""Replay throughput benchmark (FA-1a). Synthetic data only; no network.

Builds a SYNTHETIC fixture of N quote events for several SPY call contracts
(one complete trade near the start, occasional invalid inputs, then a long
quiet tail), runs a fresh trading run through ``run_to_end`` in a temporary
database, and reports total time, time per event, how per-event cost changes
from the first to the last tenth of the run, and peak memory.

Each size runs in its own subprocess so peak memory is per size.

    python tools/bench_replay.py                     # default sizes
    python tools/bench_replay.py --sizes 1000 4000 16000
    python tools/bench_replay.py --sizes 4000 --profile   # cProfile top functions

Uses only interfaces that also exist in the Step 7 code (``init_sample``,
``load_fixture``, ``start_trading``, ``run_to_end``), so the same script can
measure older branches for comparison (run it with that branch on PYTHONPATH).
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import subprocess
import sys
import tempfile
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DAY = datetime(2026, 9, 29, tzinfo=timezone.utc)
OPEN, CLOSE = DAY.replace(hour=13, minute=30), DAY.replace(hour=20)
N_CONTRACTS = 8


def _ts(dt: datetime) -> str:
    s = dt.strftime("%Y-%m-%dT%H:%M:%S.%f").rstrip("0").rstrip(".")
    return s + "Z"


def build_fixture(n_quotes: int) -> dict:
    from paper_trading.market_data.fixtures import compute_checksum

    contracts = []
    for i in range(N_CONTRACTS):
        strike = 60000 + 100 * i
        contracts.append({
            "schema_version": "1.0", "contract_id": f"SPY_20261030_C_{strike}", "underlying": "SPY",
            "expiration_date": "2026-10-30", "option_type": "CALL", "strike_cents": strike, "currency": "USD",
            "multiplier": 100, "deliverable": "100_SPY_SHARES", "exercise_style": "AMERICAN",
            "settlement_type": "PHYSICAL", "adjusted": False})
    start = DAY.replace(hour=14)
    step = min(1.0, (CLOSE - start - timedelta(minutes=1)).total_seconds() / n_quotes)
    events = [{"event_type": "SESSION_OPEN", "at": _ts(OPEN), "ref": "open"}]
    for k in range(n_quotes):
        t = start + timedelta(seconds=k * step)
        i = k % N_CONTRACTS
        seq = k + 1
        if i == 0:  # the contract the strategy selects: entry near 4.00, then a profit-target bid
            bid, ask = (390, 400) if k < 40 * N_CONTRACTS else (480, 490)
        else:
            bid, ask = 300 - 20 * i, 310 - 20 * i
        if k % 97 == 50:  # an invalid input now and then (crossed market) -> rejected with reasons
            bid, ask = ask + 5, ask
        inp = {"source": "synthetic_fixture_v1", "is_sample": True, "source_sequence": seq,
               "contract_id": contracts[i]["contract_id"], "observed_at": _ts(t), "bid_cents": bid,
               "ask_cents": ask, "bid_size": 10, "ask_size": 10, "underlying_price_cents": 60000,
               "underlying_observed_at": _ts(t), "session_reference_cents": 59700}
        events.append({"event_type": "QUOTE", "at": _ts(t), "ref": f"q{seq}", "input": inp})
    events.append({"event_type": "SESSION_CLOSE", "at": _ts(CLOSE), "ref": "close"})
    doc = {
        "fixture_schema_version": "1.0", "fixture_id": f"bench_{n_quotes}", "fixture_version": "1.0.0",
        "checksum": "", "source": "synthetic_fixture_v1", "is_sample": True,
        "data_label": "SYNTHETIC SAMPLE DATA - BENCHMARK - NOT REAL MARKET DATA",
        "description": "Replay throughput benchmark (generated by tools/bench_replay.py).", "underlying": "SPY",
        "session": {"timezone": "America/New_York", "start": _ts(OPEN), "end": _ts(CLOSE)},
        "session_reference_cents": 59700, "contracts": contracts, "events": events,
    }
    doc["checksum"] = compute_checksum(doc)
    return doc


def _store_stream(conn, n_quotes: int) -> tuple[str, str]:
    from paper_trading.market_data.datasets import store_dataset

    ds_id, label = f"bench_stream_{n_quotes}", "SYNTHETIC SAMPLE DATA - BENCHMARK - NOT REAL MARKET DATA"
    contracts = build_fixture(1)["contracts"]
    manifest = {"manifest_schema_version": "1.0", "dataset_id": ds_id, "dataset_version": "1.0.0",
                "data_class": "SYNTHETIC", "source": "synthetic_stream_v1", "label": label,
                "description": "Replay throughput benchmark (tools/bench_replay.py).",
                "generator": {"name": "tools/bench_replay.py", "version": "1"},
                "checksum_scheme": "event_stream_v1", "calendar_id": "xnys_2023_2026_v1"}
    store_dataset(conn, dataset_id=ds_id, dataset_version="1.0.0", data_class="SYNTHETIC",
                  source="synthetic_stream_v1", label=label, session_start=_ts(OPEN), session_end=_ts(CLOSE),
                  session_reference_cents=59700, contracts=contracts, events=_lazy_events(n_quotes),
                  manifest=manifest, calendar_id="xnys_2023_2026_v1")
    return ds_id, "1.0.0"


def _lazy_events(n_quotes: int):
    """Truly lazy generator (no full document in memory)."""
    contracts = [f"SPY_20261030_C_{60000 + 100 * i}" for i in range(N_CONTRACTS)]
    start = DAY.replace(hour=14)
    step = min(1.0, (CLOSE - start - timedelta(minutes=1)).total_seconds() / n_quotes)
    yield {"event_type": "SESSION_OPEN", "at": _ts(OPEN), "ref": "open"}
    for k in range(n_quotes):
        t = start + timedelta(seconds=k * step)
        i = k % N_CONTRACTS
        if i == 0:
            bid, ask = (390, 400) if k < 40 * N_CONTRACTS else (480, 490)
        else:
            bid, ask = 300 - 20 * i, 310 - 20 * i
        if k % 97 == 50:
            bid, ask = ask + 5, ask
        yield {"event_type": "QUOTE", "at": _ts(t), "ref": f"q{k + 1}", "input": {
            "source": "synthetic_stream_v1", "is_sample": True, "source_sequence": k + 1,
            "contract_id": contracts[i], "observed_at": _ts(t), "bid_cents": bid, "ask_cents": ask,
            "bid_size": 10, "ask_size": 10, "underlying_price_cents": 60000, "underlying_observed_at": _ts(t),
            "session_reference_cents": 59700}}
    yield {"event_type": "SESSION_CLOSE", "at": _ts(CLOSE), "ref": "close"}


def run_one(n_quotes: int, profile: bool, stream: bool = False, risk_limit: int = 0) -> dict:
    """Runs in a child process: one fresh database, one trading run."""
    import resource

    from paper_trading.accounting import compute_snapshot, reconcile
    from paper_trading.app import replay
    from paper_trading.app.coordinator import init_sample
    from paper_trading.config import Settings
    from paper_trading.market_data.fixtures import read_fixture_file
    from paper_trading.storage.db import connect

    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "bench.json"
        if not stream:
            path.write_text(json.dumps(build_fixture(n_quotes)), encoding="utf-8")
        extra = {"entry_risk_limit_bps": risk_limit} if risk_limit else {}
        settings = Settings(_env_file=None, db_path=Path(tmp) / "bench.sqlite3", sample_run_key="bench",
                            session_start=_ts(OPEN), session_end=_ts(CLOSE), **extra)
        conn = connect(settings.db_path, create=True)
        init = init_sample(conn, settings, trading=True)
        t0 = time.perf_counter()
        if stream:
            ds = _store_stream(conn, n_quotes)
            replay.attach_dataset(conn, init.run_id, *ds)
        else:
            doc, content = read_fixture_file(path)
            replay.load_fixture(conn, init.run_id, doc, content)
            del doc, content
        load_s = time.perf_counter() - t0
        rss_after_load = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024
        replay.start_trading(conn, init.run_id, "bench-start")

        durations: list[float] = []
        inner = replay._step_in_transaction

        def timed(c, run_id):
            s = time.perf_counter()
            try:
                return inner(c, run_id)
            finally:
                durations.append(time.perf_counter() - s)

        replay._step_in_transaction = timed
        prof = None
        if profile:
            import cProfile
            prof = cProfile.Profile()
            prof.enable()
        t0 = time.perf_counter()
        result = replay.run_to_end(conn, init.run_id, "bench-run")
        total_s = time.perf_counter() - t0
        if prof:
            prof.disable()
        events = result["steps_executed"]
        tenth = max(1, events // 10)
        rec = reconcile(conn, init.run_id)
        snap = compute_snapshot(conn, init.account_id)
        trades = conn.execute("SELECT COUNT(*), COALESCE(SUM(realized_pnl_cents),0) FROM closed_trades").fetchone()
        out = {
            "quotes": n_quotes, "events": events, "load_s": round(load_s, 3), "total_s": round(total_s, 3),
            "ms_per_event": round(1000 * total_s / events, 3),
            "first_tenth_ms": round(1000 * sum(durations[:tenth]) / tenth, 3),
            "last_tenth_ms": round(1000 * sum(durations[-tenth:]) / tenth, 3),
            "peak_after_load_mb": round(rss_after_load, 1),
            "peak_rss_mb": round(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024, 1),
            "db_mb": round(os.path.getsize(settings.db_path) / 2**20, 1),
            "reconciled": rec.ok, "trades": trades[0], "realized_cents": trades[1],
            "final_cash_cents": snap.cash_cents,
            "risk_rejections": conn.execute(
                "SELECT COUNT(*) FROM risk_decisions WHERE decision = 'REJECTED'").fetchone()[0],
            "accepted": conn.execute("SELECT COUNT(*) FROM market_quotes").fetchone()[0],
            "rejected": conn.execute("SELECT COUNT(*) FROM rejected_inputs").fetchone()[0],
        }
        conn.close()
        if prof:
            import io
            import pstats
            buf = io.StringIO()
            pstats.Stats(prof, stream=buf).sort_stats("cumulative").print_stats(25)
            out["profile"] = buf.getvalue()
        return out


def hardware() -> str:
    cpu = platform.processor() or platform.machine()
    try:
        for line in Path("/proc/cpuinfo").read_text().splitlines():
            if line.startswith("model name"):
                cpu = line.split(":", 1)[1].strip()
                break
    except OSError:
        pass
    mem = ""
    try:
        kb = int(Path("/proc/meminfo").read_text().split()[1])
        mem = f", {kb / 2**20:.1f} GiB RAM"
    except (OSError, ValueError, IndexError):
        pass
    import sqlite3
    return (f"{cpu}, {os.cpu_count()} logical CPUs{mem}; {platform.system()} {platform.release()}; "
            f"Python {platform.python_version()}; SQLite {sqlite3.sqlite_version}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sizes", type=int, nargs="+", default=[1000, 2000, 4000, 8000, 16000])
    ap.add_argument("--profile", action="store_true")
    ap.add_argument("--json", action="store_true", help="print raw JSON rows")
    ap.add_argument("--stream", action="store_true",
                    help="store an event-stream dataset from a generator (FA-1a engine only) instead of a fixture")
    ap.add_argument("--entry-risk-limit-bps", type=int, default=0,
                    help="stress case: e.g. 1 ($10 on $100k) makes risk reject every entry signal")
    ap.add_argument("--child", type=int, help=argparse.SUPPRESS)
    args = ap.parse_args()
    if args.child:
        print(json.dumps(run_one(args.child, args.profile, args.stream, args.entry_risk_limit_bps)))
        return 0

    print("hardware:", hardware())
    print("input:", "event-stream dataset stored from a generator" if args.stream else "JSON fixture file")
    header = (f"{'quotes':>7} {'events':>7} {'load s':>7} {'replay s':>9} {'ms/event':>9} "
              f"{'first10%':>9} {'last10%':>8} {'load MB':>8} {'peak MB':>8} {'db MB':>6}  books  trades  realized"
              f"  risk-rejected")
    print(header)
    rows = []
    for n in args.sizes:
        cmd = ([sys.executable, __file__, "--child", str(n)] + (["--profile"] if args.profile else [])
               + (["--stream"] if args.stream else [])
               + ["--entry-risk-limit-bps", str(args.entry_risk_limit_bps)])
        proc = subprocess.run(cmd, capture_output=True, text=True, env={**os.environ, "PYTHONPATH": os.environ.get(
            "PYTHONPATH", str(ROOT))})
        if proc.returncode:
            print(proc.stderr, file=sys.stderr)
            return proc.returncode
        r = json.loads(proc.stdout.strip().splitlines()[-1])
        rows.append(r)
        print(f"{r['quotes']:>7} {r['events']:>7} {r['load_s']:>7} {r['total_s']:>9} {r['ms_per_event']:>9} "
              f"{r['first_tenth_ms']:>9} {r['last_tenth_ms']:>8} {r.get('peak_after_load_mb', '-'):>8} "
              f"{r['peak_rss_mb']:>8} {r['db_mb']:>6}  "
              f"{'OK' if r['reconciled'] else 'FAIL':<5}  {r['trades']:>6}  {r['realized_cents']:>8}  "
              f"{r.get('risk_rejections', '-'):>13}")
        if args.profile:
            print(r["profile"])
    if args.json:
        print(json.dumps(rows, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
