/**
 * Generate supabase/seed.sql from the bundled question bank (data/questions).
 *   npm run db:seed-sql
 * The output is idempotent: re-running it upserts by deterministic ids.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";

import { TOPICS } from "../src/lib/config/topics";
import { buildSeedBank } from "../src/lib/questions/seed-builder";
import { loadJsonFiles } from "./load-json-files";

function lit(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function textArray(values: string[]): string {
  return values.length ? `array[${values.map(lit).join(", ")}]::text[]` : "'{}'::text[]";
}

const files = loadJsonFiles([path.resolve("data/questions")]);
const bank = buildSeedBank(files.map((f) => f.data));
if (bank.issues.length) {
  console.error(bank.issues);
  throw new Error("Seed questions contain validation errors; run npm run questions:validate");
}

const topicDefs = new Map(TOPICS.map((t) => [t.id, t]));
const out: string[] = [];
out.push("-- Generated by scripts/generate-seed-sql.ts. Do not edit by hand.");
out.push(`-- ${bank.questions.length} questions, ${bank.topics.length} topics.`);
out.push("begin;");
out.push("");
out.push("insert into public.topics (id, name, domain_hint, keywords) values");
out.push(
  bank.topics
    .map((t) => {
      const def = topicDefs.get(t.id);
      return `  (${lit(t.id)}, ${lit(t.name)}, ${def ? def.domainHint : "null"}, ${textArray(def?.keywords ?? [])})`;
    })
    .join(",\n") +
    "\non conflict (id) do update set name = excluded.name, domain_hint = excluded.domain_hint, keywords = excluded.keywords;",
);
out.push("");

for (const q of bank.questions) {
  out.push(
    `insert into public.questions (id, stem, domain_id, difficulty, question_type, correct_count, explanation, exam_clue, memory_tip, is_scenario, status, created_at, updated_at) values (${[
      lit(q.id),
      lit(q.stem),
      q.domainId,
      lit(q.difficulty),
      lit(q.questionType),
      q.correctCount,
      lit(q.explanation),
      lit(q.examClue),
      lit(q.memoryTip),
      q.isScenario,
      lit(q.status),
      lit(q.createdAt),
      lit(q.updatedAt),
    ].join(", ")})\non conflict (id) do update set stem = excluded.stem, domain_id = excluded.domain_id, difficulty = excluded.difficulty, question_type = excluded.question_type, correct_count = excluded.correct_count, explanation = excluded.explanation, exam_clue = excluded.exam_clue, memory_tip = excluded.memory_tip, is_scenario = excluded.is_scenario, status = excluded.status;`,
  );
  out.push(
    "insert into public.question_choices (id, question_id, position, body, is_correct, explanation) values\n" +
      q.choices
        .map((c, i) => `  (${lit(c.id)}, ${lit(q.id)}, ${i}, ${lit(c.text)}, ${c.isCorrect}, ${lit(c.explanation)})`)
        .join(",\n") +
      "\non conflict (id) do update set position = excluded.position, body = excluded.body, is_correct = excluded.is_correct, explanation = excluded.explanation;",
  );
  out.push(
    "insert into public.question_topics (question_id, topic_id) values " +
      q.topics.map((t) => `(${lit(q.id)}, ${lit(t)})`).join(", ") +
      " on conflict do nothing;",
  );
  out.push("");
}
out.push("commit;");

const target = path.resolve("supabase/seed.sql");
writeFileSync(target, out.join("\n") + "\n");
console.log(`Wrote ${bank.questions.length} questions and ${bank.topics.length} topics to ${path.relative(process.cwd(), target)}`);
